replicaCount: 1

service:
  port: 31111

image:
  repository: ci-example
  tag: 53ce0ae-SNAPSHOT
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 750m
    memory: 2.5Gi
  requests:
    cpu: 250m
    memory: 1Gi

nodeSelector: {}
tolerations: []
affinity: {}