replicaCount: 1

service:
  port: 31111

image:
  repository: ci-example
  tag: 53ce0ae-SNAPSHOT
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}